development:
  secret_key_base: d90c6ebeb5dab5a3af294bdc61b4ed631c6e1b07f12e9c2f6b11546e391d6f00f7543375e352765e8670f241c118e1d416296782e96584dcf1fc89804c2298b7
  jwt_expiration_seconds: <%= ENV['JWT_EXPIRATION_SECONDS'] %>
  sms:
    login: <%= ENV['SMS_LOGIN'] %>
    password: <%= ENV['SMS_PASSWORD'] %>
  mapbox:
    access_token: <%= ENV['MAPBOX_ACCESS_TOKEN'] %>
  google_maps:
    key: <%= ENV['GOOGLE_MAPS_KEY'] %>
  cloud_payments:
    public_key: <%= ENV['CLOUD_PAYMENTS_PUBLIC_KEY'] %>
    secret_key: <%= ENV['CLOUD_PAYMENTS_SECRET_KEY'] %>
  firebas:
    auth_token: <%= ENV['FCM_AUTH_TOKEN'] %>

test:
  secret_key_base: 1b5476b58a2a948cb267e03d3edb4c33ac894f6b2403af796fd3b907c2bb0520eead2d22c401f541258f6932ad214b3223d16620f7edf5b7ec76f0f08bf9de85
  jwt_expiration_seconds: <%= ENV['JWT_EXPIRATION_SECONDS'] %>
  sms:
    login: <%= ENV['SMS_LOGIN'] %>
    password: <%= ENV['SMS_PASSWORD'] %>
  mapbox:
    access_token: <%= ENV['MAPBOX_ACCESS_TOKEN'] %>
  google_maps:
    key: <%= ENV['GOOGLE_MAPS_KEY'] %>
  cloud_payments:
    public_key: <%= ENV['CLOUD_PAYMENTS_PUBLIC_KEY'] %>
    secret_key: <%= ENV['CLOUD_PAYMENTS_SECRET_KEY'] %>
  firebas:
    auth_token: <%= ENV['FCM_AUTH_TOKEN'] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  jwt_expiration_seconds: <%= ENV['JWT_EXPIRATION_SECONDS'] %>
  sms:
    login: <%= ENV['SMS_LOGIN'] %>
    password: <%= ENV['SMS_PASSWORD'] %>
  mapbox:
    access_token: <%= ENV['MAPBOX_ACCESS_TOKEN'] %>
  google_maps:
    key: <%= ENV['GOOGLE_MAPS_KEY'] %>
  cloud_payments:
    public_key: <%= ENV['CLOUD_PAYMENTS_PUBLIC_KEY'] %>
    secret_key: <%= ENV['CLOUD_PAYMENTS_SECRET_KEY'] %>
  firebas:
    auth_token: <%= ENV['FCM_AUTH_TOKEN'] %>
